[server]
    url = "127.0.0.1:8000"
    do_timestamps = true
    user = "root"
    password = "password"

[general]
    log_file = "~/spittal.log"
    log_level = "DEBUG"

[upload]
    # Optionally, set a default upload directory prefix.
    upload_directory_path = "./"
    [dict.areaperil]
        file_path = "MyAreaPerilDict_Oasis.csv"
        module_supplier_id = 3
    [dict.event]
        module_supplier_id = 3
    [dict.hazfp]
        module_supplier_id = 3
    [dict.vuln]
        module_supplier_id = 3

[workflow]
    upload_files = true
    create_file_uploads = true
    create_file_downloads = true
