# This file is separated into different logical section of an Oasis workflow.
# Each section specified will be run based on key value pairs define in it.
# Essentially, each section conveniently runs many underlying webservices.
# The sections will be run in order.

[meta]
url = "http://127.0.0.1:8000"
log_file = "spittal.log"
log_level = "DEBUG"
system_config = 1

[login]
user = "root"
password = "password"

[model]
name = "My test model"
do_timestamps = true
key = "Model key"

# Optionally, set a default upload directory prefix.
directory_path = "./"

  [model.dict.areaperil]
  filename = "MyAreaPerilDict_Oasis.csv"
  module_supplier_id = 3

  [model.dict.event]
  filename = "lkj.csv"
  module_supplier_id = 3

[exposure]
name = "My test exposure"
do_timestamps = true

# Optionally, set a default upload directory prefix.
directory_path = "./"

  [exposure.dict.exposure]
  filename = "MyExposureDict.csv"
  module_supplier_id = 2

  [exposure.version.exposure]
  filepath = "MyExposureVersion.csv"
  module_supplier_id = 2

[benchmark]
name = "my benchmark"
chunk_size = 10
min_chunk = 3
max_chunk = 10
